### ISSUE TITLE
How To Properly Precompile JSX In the Asset Pipeline

### ISSUE THREAD

**Issue by ossrapaport-zz** [ossrapaport/collegium#3]
@harimohanraj89 @WilliamfShaw @DrRobotmck @bigtone1284 
# Context

<hr>
## USER STORY

As a user, I want to be able to be able to log in.
## WHAT I AM TRYING TO DO

I want to be able to use the application.html.erb as a starting point, much as we did when implementing Backbars in Rails, and build a single-page web application off of that. In order to do so, I need to be able to render my React.js code onto the DOM. I have not been able to do so yet.
## DETAILED DESCRIPTION OF THE BUG/ERROR

React.js is a JavaScript framework in the style of Backbone and Angular. However, React is solely the view. In order to allow for full functionality despite this, React uses JSX (a mix of JavaScript and HTML) as its language. A Ruby on Rails does not automatically understand JSX unlike JavaScript, so I precompile the JSX into JavaScript before passing it on to the server for rendering. I am able to reach the precompiling state but am now having trouble getting the text to show on the page. The error I receive is:

`uninitialized constant ActionView::CompiledTemplates::App`

The files involved in this error are: application.html.erb, application.js, and test.js.jsx. I am unsure if seeing the code would help as it's more a general problem than a specific issue with the code. But, if desired, I am happy to screenshot it. Please just make a note in the comments for any or all code.
# WHAT I'VE TRIED

<hr>

I have scoured the web for resources about combining Rails and React and while there is of course a lot of information out there have been unsuccessful. The "react-rails" gem, which I have downloaded, is doing the compilation but I am unable to get anything up on the screen.
# QUESTION

<hr>

How do I actually integrate React and Rails? All I need is to make that first connection and then I will be able to do the rest.

Thank you.
- Owen

**Comment by harimohanraj89** [comment]
Have you pushed your latest code?

**Comment by ossrapaport-zz** [comment]
Just put in a pull request with the latest code. I will merge if you want

**Comment by ossrapaport-zz** [comment]
Figured it out
