### ISSUE TITLE
Uploading Files to AWS S3

### ISSUE THREAD

**Issue by ossrapaport-zz** [ossrapaport/collegium#5]
@WilliamfShaw @bigtone1284 @harimohanraj89 @DrRobotmck 
# USER STORY

I am working on the user story "As a user, I want to be able to upload my documents." This is the `aws` branch of my repository.
# What I Am Trying To Do

I want the user to be able to upload a file from his computer and, once that file has been uploaded to my application using the HTML file input, I want to send that file to Amazon Web Services S3 to make an entry in my bucket. 
# Detailed Description of the Error

The user clicks "Choose file", which is a file input that HTML5 offers, and then selects a file from his computer. He then submits the form. I then get the file data (as best as I can) from that input which looks like this:

```
File {webkitRelativePath: "", lastModified: 1423588885000, lastModifiedDate: Tue Feb 10 2015 12:21:25 GMT-0500 (EST), name: "Voting Form.pdf", type: "application/pdf"…}
lastModified: 1423588885000
lastModifiedDate: Tue Feb 10 2015 12:21:25 GMT-0500 (EST)
name: "Voting Form.pdf"
size: 385511
type: "application/pdf"
webkitRelativePath: ""
__proto__: File
```

This information looks a lot like metadata, leading me to believe that there is more data somewhere inside this (maybe hidden from the browser). I then want to upload this to S3. To do so, I have two choices: either upload to S3 from the browser or send this information to the backend and upload from there.

In order to achieve the former (directly uploading from the browser), I would need to access the AWS object in the browser. As far as I can tell, this is not possible with Rails because there is no gem to support this. In a regular index.html, this is possible though because there is a special script tag from Amazon. 

The other option is to send the file back somehow (jQuery responds with an illegal invocation error when I try to do so because I can't send that type of object I guess). Once I have it back, I would also need to access the body of the file and then make a call to S3 from the backend (which I can do). 
# What I've Tried

I have looked around to handle uploading files and at many different gems. If I can get the file to the backend I can likely upload it. And if I can upload it from the front-end that would be even better.
# Question

How can I upload the user's file? Is doing it from the browser possible?

**Comment by WilliamfShaw** [comment]
Have you looked into the Carrierwave gem for rails?

**Comment by WilliamfShaw** [comment]
@ossrapaport

**Comment by ossrapaport-zz** [comment]
Yes but I need to somehow get the information to the backend first

**Comment by WilliamfShaw** [comment]
@ossrapaport so you want to save to your backend and aws?

**Comment by ossrapaport-zz** [comment]
Now I have it as a base64 encoded string which I am going to try to upload to Amazon - will keep you updated

**Comment by ossrapaport-zz** [comment]
It is not going anywhere, I am unsure how to proceed

**Comment by WilliamfShaw** [comment]
@ossrapaport can you push your most recent code?

**Comment by ossrapaport-zz** [comment]
Yea I will

**Comment by ossrapaport-zz** [comment]
It's up in a pull request as a branch "aws"

**Comment by harimohanraj89** [comment]
What is the status of this issue? @ossrapaport

**Comment by ossrapaport-zz** [comment]
I am still unable to upload to S3 but can do everything I want in local. I will contact Sarah for Digital Ocean credits. Closed!
